add 'hearders' arg to methods create, update and delete
codeaffen/pyhpipam pull request #58
Opened 2022-08-03 15:31 UTC by positiveEV

Here is my PR as asked in #57.

2022-08-03 16:30 UTC, cmeissner commented
@positiveEV thank you for submitting your first PR. To get it merged you need to fix some small things. 

1. Format the title sth like "Fix <issue-id> - short description of issue"
2. Add a description what you have changed
3. Add a change log entry use `changelog` command (came from requirements-dev.txt)
4. Add a test case for the use case which is covered by your PR
    As you can't provide any steps to reproduce the issue the test case can't only check the success but not the failure state
    
After that I think we can merge the PR as it seems not to interfere the existing test cases.

2022-08-13 12:26 UTC, cmeissner requested changes
LGTM but test case is still missing

2022-08-13 14:30 UTC, positiveEV commented
Sorry, for not coming back at you earlier.
Regarding the test case if I write a ensure_address.py, and pass a headers arg to create_entity, will it be ok?

2022-08-13 14:56 UTC, cmeissner commented
No matter. I had some time today to fix some points of the list. Two last things:

1. Can you please add headers parameter also to `get_entity` method?
2. Regarding the test case. As we can't reproduce the issue the test should test the documented feature to change the output from json to xml with `Content-Type: application/xml`. Here would be a ensure_address (CRUD test) a good idea. But instead of working with json responses work with xml instead.

2023-10-21 08:13 UTC, cmeissner requested changes
This does not work out. If you run `pi.get_entity(controller='subnets', controller_path='1', headers={'Content-Type': 'application/xml'})` you run into an exception.

2023-10-21 08:13 UTC, cmeissner commented on phpypam/core/api.py
> +        return self._query(token=self._api_token, method=GET, path=_path, params=_params, headers=None)
This is an error, you need to pass `_headers` here.

2023-12-05 13:17 UTC, cmeissner commented
This PR was closed because it has been stalled for 15 days with no activity.

2023-12-05 13:17 UTC, closed without merging